### ISSUE TITLE
Mysql Duplicate Horse when server Crash or force quit.

### ISSUE THREAD

**Issue by chocolatecraft** [7rory768/RPGHorses#1]
Mysql Duplicate Horse when server Crash or force quit.

When I force close cmd or crash. and then start server Horse will duplicated.

In addition, Players join to server data will duplicated until they disconnect data will remove it. If force quit or crash Database still not remove duplicated data from sql.

**Comment by 7rory768** [comment]
Are you able to send a screenshot of your table before duplication and after? Also, were ANY of the horses put into the market at all? even for just a moment?

**Comment by chocolatecraft** [comment]
No I disable Market function.

I gonna explain to screenshot.

1.First time to join I got 1 horse from config.
https://i.ibb.co/zSQ2XvX/1.png

2.I leave from server and comeback again I got duplicate datta from join to server
https://i.ibb.co/h1wY9Mh/2.png

3.I leave from server again. Duplicate data disappear from server when I disconnect.
https://i.ibb.co/Xjg05kX/3.png

4.And then I join server (and force quit or server crash ) Data remain 2 row Because when I join I got duplicated
(this picture when server closed)
https://i.ibb.co/GMvnqMN/4.png

5. Until I start server and then I join server Data duplicated and Duplicated and I have 2 horse.
https://i.ibb.co/KychGR5/5.png

https://i.ibb.co/9smCwMz/6.png

**Comment by 7rory768** [comment]
Fixed in commit #4daa601
